### ISSUE TITLE
[beta 3 only] Issues with user ubuntu's home directory

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/nitro#145]
Maybe it's me doing something wrong, but I have some issues with the just released beta 3 and initializing a new machine:

- user ubuntu's home is not initialized with /etc/skel (no .profile, no .bashrc)
- user ubuntu' home has some weird permissions (owned by root), is this normal behavior?
- home has an empty .composer directory and composer doesn't seem to be installed

Anyone else seeing those?

**Comment by jasonmccallister** [comment]
Hi @JeanLucEsser, that is definitely strange. Can you run `nitro context` and `nitro info` and provide the output here?

It sounds like this is a new machine, but if you came from beta 2, can you run `nitro refresh`? 

I have a feeling that the initialization process failed - and did not complete the rest of the scripts to setup. Can you run provide the log files from these commands?

1. `multipass transfer nitro-dev:/var/log/cloud-init-output.log cloud-init-output.log`
2. `multipass transfer nitro-dev:/var/log/cloud-init.log cloud-init.log`

That should give you a `cloud-init-output.log` and `cloud-init.log`

**Comment by JeanLucEsser** [comment]
Here you go: I destroyed my previous machine and init a new nitro-dev.

`nitro context`
```
Using config: /Users/sierraromeo/.nitro/nitro-dev.yaml
------
php: "7.4"
mounts:
  - source: ~/Sites/vlp
    dest: /home/ubuntu/sites/vlp.test
  - source: ~/Sites/lecontactmoderne
    dest: /home/ubuntu/sites/lecontactmoderne.test
databases:
  - engine: mysql
    version: "5.7"
    port: "3306"
sites:
  - hostname: vlp.test
    webroot: /home/ubuntu/sites/vlp.test/web
  - hostname: lecontactmoderne.test
    webroot: /home/ubuntu/sites/lecontactmoderne.test/web
```

`nitro info`
```
Name:           nitro-dev
State:          Running
IPv4:           192.168.64.2
Release:        Ubuntu 18.04.4 LTS
Image hash:     3b2e3aaaebf2 (Ubuntu 18.04 LTS)
Load:           0.18 0.12 0.09
Disk usage:     2.7G out of 38.6G
Memory usage:   364.5M out of 3.9G
Mounts:         /Users/sierraromeo/Sites/vlp              => /home/ubuntu/sites/vlp.test
                    UID map: 501:default
                    GID map: 20:default
                /Users/sierraromeo/Sites/lecontactmoderne => /home/ubuntu/sites/lecontactmoderne.test
                    UID map: 501:default
                    GID map: 20:default
```

I ran `nitro refresh` just to make sure but no change:
```
Downloading the latest refresh script
Refreshed the templates and configs for the machine to  1.0.0-beta.3
```

Requested logs attached:
[cloud-init-output.log](https://github.com/craftcms/nitro/files/4656824/cloud-init-output.log)
[cloud-init.log](https://github.com/craftcms/nitro/files/4656825/cloud-init.log)

**Comment by jasonmccallister** [comment]
If you run `nitro ssh` do you get any errors inside of the machine?

**Comment by jasonmccallister** [comment]
I identified an issue with the refresh script, can you run `nitro refresh` command again?

**Comment by JeanLucEsser** [comment]
I have 0 errors inside the machine, sites are working, I installed composer on my own, changed owner of ubuntu and it's working as well. I just ran `nitro refresh` again. As I have no errors it's difficult to see if it changed anything. Should I try and create another machine?

**Comment by JeanLucEsser** [comment]
BTW, aren't new machines supposed to be 20.04? Because I'm stuck at 18.04, even for new machines. From release notes: [7a5fc04](https://github.com/craftcms/nitro/commit/7a5fc04d78667f5d52ddf35c556ed13820b438e4) New mahcines will use 20.04 LTS

**Comment by jasonmccallister** [comment]
@JeanLucEsser in this beta, the output of the scripts were not being displayed - there was an issue in the script that was fixed here: https://github.com/craftcms/nitro/commit/209a24f32deb6ae415c4aedc360fe4568478b54f.

As far as 20.04, I had to revert that change. Docker just tagged the versions for 20.04 today so we will most likely change it back to 20.04 in the next beta version.

If everything is working, besides composer - which I identified that issue and will fix soon, running `nitro refresh` should set the permissions on home folders.

Also, if you run `nitro ssh` can you run `ls -la` and provide the output?

**Comment by JeanLucEsser** [comment]
On a new machine 'nitro-refresh', after running `nitro refresh -m nitro-refresh` on it:

`ls -la`
```
total 24
drwxr-xr-x 6 root   root   4096 May 20 19:12 .
drwxr-xr-x 3 root   root   4096 May 20 19:10 ..
drwxr-xr-x 2 root   root   4096 May 20 19:11 .composer
drwxr-xr-x 3 ubuntu ubuntu 4096 May 20 19:10 .nitro
drwx------ 2 ubuntu ubuntu 4096 May 20 19:10 .ssh
drwxr-xr-x 2 ubuntu ubuntu 4096 May 20 19:12 sites
```

`mkdir test`
```
mkdir: cannot create directory ‘test’: Permission denied
```

As you can see, skeleton from /etc/skel/ (bashrc and company) still missing, owner of ubuntu is root.

**Comment by jasonmccallister** [comment]
Ahh, I see what you are saying. Let me look into this and we should be able to resolve with the next beta.

**Comment by jasonmccallister** [comment]
Ok, this should be resolved in the next beta (4). For now you can set your permissions manually:

1. `nitro ssh`
2. `sudo chown -R ubuntu:ubuntu /home/ubuntu`

The composer installation should be resolved as well.
